### ISSUE TITLE
Fixes in readme and Dockerfile

### ISSUE THREAD

**Issue by thaJeztah** [oren/test-alpine#1]
Just saw your question on IRC;

The reason it's not working with `docker-compose run`, is that the `run` command is not the direct equivalent to `docker run`; `docker-compose run` is intended to run one-off commands and, by default, doesn't publish ports (unless you're adding `--service-ports` flag (see the [documentation](https://docs.docker.com/compose/cli/#run))

You are probably looking for `docker-compose up -d`, which will build (if it doesn't exist yet) the image and start the container in the background (because of the `-d` flag).

**_However**_, your `docker-compose.yml` doesn't have a `command:`, so the `server.js` will not be executed (just `node`), so you might want to add that (or add it to the `CMD` in your Dockerfile)

I noticed you're not using the [official iojs image](https://registry.hub.docker.com/_/iojs/), but the alpine image; probably because you want a smaller image. However, you're using separate `RUN` instructions for each line. In Docker, each `RUN` is executed in a new layer (which is basically a new container/image); therefore the `rm -rf ...` line will _not_ result in a smaller image, because those files are already included in a previous layer. The best way to resolve this, is to _combine_ the instructions, so that they are all executed in a single layer (see [dockerfile best practices](https://docs.docker.com/articles/dockerfile_best-practices/))

Something like below (remember to force a rebuild using `docker-compose build` after changing). I haven't tested the Dockerfile, but I think it should work. Good luck!

``` Dockerfile
FROM alpine:edge
RUN echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories 
RUN apk update \
 && apk add --update iojs \
 && apk update \
 && apk upgrade \
 && rm -rf /var/cache/apk/*
WORKDIR /src
COPY . /src
EXPOSE 3000
CMD ["node", "/src/server.js"]
```

**Comment by oren** [comment]
thank you! everything works now.
